### ISSUE TITLE
The messages I sent are displayed incorrectly

### ISSUE THREAD

**Issue by GitesClone** [RTippin/messenger-ui#1]
Hello! When I send a message, it does not stand out that I sent it. My and the other person's messages are displayed on the left, although mine should be displayed on the right and highlighted in blue. Everything works in the demo version, but installing this package Laravel 8 and Jetstream works incorrectly.

![image](https://user-images.githubusercontent.com/89775437/131317103-4ea71e94-5f6d-402b-ac38-b4e75a3259c6.png)

**Comment by RTippin** [comment]
My demo is setup to use UUIDs, and my config in `messenger.provider_uuids` is true. When you installed into a fresh application, are your users using INT / auto-incrementing primary keys now? If they are, you need to be sure to set `provider_uuids` to false/true to match your user model key types. This used to be a bug, but was fixed some time ago (in my UI since I support UUID or auto-incrementing). Can you check your config in `messenger` and see if that fixes it?

**Comment by RTippin** [comment]
I have identified the issue and will be implementing a fix shortly. When providers do not use morph maps, the FQN of the model is not parsed correctly into my `Messenger.js` manager.

**Comment by RTippin** [comment]
@GitesClone This issue has been resolved with my latest version `v1.1.0`. Be sure to `composer update`, then re-publish my JS assets: `php artisan vendor:publish --tag=messenger-ui.assets --force`
